import { Target, Send, GitBranch, Database, CalendarCheck, BarChart3, MessageSquare, Bot, Megaphone, Users, Truck, Calculator, Phone, Factory, Stethoscope, FileText, Rocket, Sprout, Search, UserSearch, Video, UserPlus, Smile, Workflow, ScanText, BadgeCheck, AlertTriangle, Network, TrendingUp, Boxes, ReceiptText, Wallet, Banknote } from 'lucide-react'

// Icon keys used across solution-detail data files.
export const CAP_ICONS = {
  target: Target,
  send: Send,
  pipeline: GitBranch,
  enrich: Database,
  calendar: CalendarCheck,
  analytics: BarChart3,
  chat: MessageSquare,
  bot: Bot,
  megaphone: Megaphone,
  users: Users,
  truck: Truck,
  finance: Calculator,
  phone: Phone,
  factory: Factory,
  health: Stethoscope,
  content: FileText,
  campaign: Rocket,
  nurture: Sprout,
  seo: Search,
  screen: UserSearch,
  interview: Video,
  onboard: UserPlus,
  engage: Smile,
  workflow: Workflow,
  document: ScanText,
  approval: BadgeCheck,
  alert: AlertTriangle,
  integration: Network,
  forecast: TrendingUp,
  inventory: Boxes,
  invoice: ReceiptText,
  expense: Wallet,
  receivable: Banknote,
}
